# -*- coding: utf-8 -*-
"""Model config in json format"""

CFG = {
    "data": {
        "indicator-1": {
            "identifier": "1",
            "name": "Large Enterprises: ICT security measures",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ['E_SECMSPSW', 'E_SECMDUO', 'E_SECMDENC', 'E_SECMOSBU', 'E_SECMNAC', 'E_SECMVPN', 'E_SECMLOG',
                          'E_SECMTST'],
            "unit": "PC_ENT",
            "size_emp": "GE250",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/1-LargeEnterprisesICTSecurityMeasures.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'average',
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-11": {
            "identifier": "11",
            "name": "SMEs: ICT security measures",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ['E_SECMSPSW', 'E_SECMDUO', 'E_SECMDENC', 'E_SECMOSBU', 'E_SECMNAC', 'E_SECMVPN', 'E_SECMLOG',
                          'E_SECMTST'],
            "unit": "PC_ENT",
            "size_emp": "10-249",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/1a-SMEsEnterprisesICTSecurityMeasures.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'average',
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-2": {
            "identifier": "2",
            "name": "Citizens: privacy and protection of personal data",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCI_PRV20",
            "ind_type": "IND_TOTAL",
            "var_codes": ["I_MAPS_5"],
            "unit": "PC_IND",
            "size_emp": None,
            "startPeriod": 2023,
            "endPeriod": 2023,
            "path": "data/eurostatIndicators/2024/2-PrivacyAndProtectionCitizens.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-4": {
            "identifier": "4",
            "name": "Large Enterprises: Staff Awareness",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ["E_SECAWANY"],
            "unit": "PC_ENT",
            "size_emp": "GE250",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/4-LargeEnterprisesStaffAwareness.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-7": {
            "identifier": "7",
            "name": "SMEs: Staff Awareness",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ["E_SECAWANY"],
            "unit": "PC_ENT",
            "size_emp": "10-249",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/4b-SMEsEnterprisesStaffAwareness.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-18": {
            "identifier": "18",
            "name": "Enterprises: risk assessment",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ["E_SECMRASS"],
            "unit": "PC_ENT",
            "size_emp": "GE10",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/18-EnterprisesRiskAssessment.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-19": {
            "identifier": "19",
            "name": "Enterprises: ICT security policy",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_RA",
            "ind_type": None,
            "var_codes": ["E_SECPOL2"],
            "unit": "PC_ENT",
            "size_emp": "GE10",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/19-EnterprisesICTSecurityPolicy.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-21": {
            "identifier": "21",
            "name": "Share of enterprises that buy security software applications as Cloud Computing Service",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CICCE_USE",
            "ind_type": None,
            "var_codes": ["E_CC_PSEC"],
            "unit": "PC_ENT",
            "size_emp": "GE10",
            "startPeriod": 2023,
            "endPeriod": 2023,
            "path": "data/eurostatIndicators/2024/21-EnterprisesBuySecurityServicesCCS.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-22": {
            "identifier": "22",
            "name": "Share of enterprises that use AI technologies for ICT security",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_EB_AI",
            "ind_type": None,
            "var_codes": ["E_AI_PITS"],
            "unit": "PC_ENT",
            "size_emp": "GE10",
            "startPeriod": 2023,
            "endPeriod": 2023,
            "path": "data/eurostatIndicators/2024/22-EnterprisesUseAIICTSecurity.xlsx",
            "computation": {"needs_computation": False,
                            "computation_alg": None,
                            "max_value": None
                            },
            "source": "Eurostat"
        },
        "indicator-25": {
            "identifier": "25",
            "name": "Large enterprises: Security Incidents - Destruction or corruption of data",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2IDCD"],
            "unit": "PC_ENT",
            "size_emp": "GE250",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/25-LargeSIDentifierestructionCorruptionData.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        },
        "indicator-26": {
            "identifier": "26",
            "name": "SMEs: Security Incidents - Destruction or corruption of data",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2IDCD"],
            "unit": "PC_ENT",
            "size_emp": "10-249",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/26-SMEsSIDentifierestructionCorruptionData.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        },
        "indicator-27": {
            "identifier": "27",
            "name": "Large enterprises: Security Incidents - Disclosure of confidential data",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2ICNF"],
            "unit": "PC_ENT",
            "size_emp": "GE250",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/27-LargeSIDentifierisclosureConfidentifierentialData.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        },
        "indicator-28": {
            "identifier": "28",
            "name": "SMEs: Security Incidents - Disclosure of confidential data ",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2ICNF"],
            "unit": "PC_ENT",
            "size_emp": "10-249",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/28-SMEsSIDentifierisclosureConfidentifierentialData.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        },
        "indicator-29": {
            "identifier": "29",
            "name": "Large enterprises: Security Incidents - Unavailability of ICT Services",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2IUSV"],
            "unit": "PC_ENT",
            "size_emp": "GE250",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/29-LargeSIUnavailabilityICTServices.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        },
        "indicator-30": {
            "identifier": "30",
            "name": "SMEs: Security Incidents - Unavailability of ICT Services",
            "countries": ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT',
                          'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'],
            "code": "ISOC_CISCE_IC",
            "ind_type": None,
            "var_codes": ["E_SEC2IUSV"],
            "unit": "PC_ENT",
            "size_emp": "10-249",
            "startPeriod": 2022,
            "endPeriod": 2022,
            "path": "data/eurostatIndicators/2024/30-SMEsSIUnavailabilityICTServices.xlsx",
            "computation": {"needs_computation": True,
                            "computation_alg": 'inverse',
                            "max_value": 100
                            },
            "source": "Eurostat"
        }
    }
}


